name: expense_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pie_chart: ^5.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\logo.png
    - assets\medicine.png
    - assets\food.png
    - assets\shopping.png
    - assets\fuel.png
    - assets\entertainment.png
    - assets\plus.png
    - assets\add.png
    - assets\image.png
    - assets\Subtract.png